collections:
  authors: #custom collection - everything inside _authors
    output: true #creates individual page

defaults: # site defaults - https://jekyllrb.com/docs/configuration/front-matter-defaults/
  - scope:
      path: "" #all files
      type: "authors" # colloction / _authors folder
    values:
      layout: "author" # layout = author auomatically applied
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

url: "https://test.aloks.com.np" # the base hostname & protocol for your site # for jekyll-sitemap

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
